Release Guidelines
Particular/ServiceControl.Monitoring pull request #212
Opened 2019-08-26 03:20 UTC by mikeminutillo

Add info about releasing ServiceControl.Monitoring

2019-08-26 19:46 UTC, SeanFeldman requested changes

2019-08-26 19:46 UTC, SeanFeldman commented on README.md
> +To release a new version of ServiceControl.Monitoring:
It would help to also include a basic guide on versioning decision making SC is using.
For example:
- For a new version of a downstream, create a minor release of SC
- Or, for a new version of SC.Monitoring, create a minor release

2019-08-26 19:46 UTC, SeanFeldman commented on README.md
> +1. Check whether the [Platform Sample](https://github.com/Particular/Particular.PlatformSample) needs to be updated
What a chack constitutes? How do I know that an update of the sample is required?

2019-08-27 08:07 UTC, andreasohlund commented
Monitoring sources have now been moved to SC. Releasing Monitoring is now fully automated via the SC release pipeline. Closing this

2019-08-27 08:07 UTC, closed without merging